version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-oh-pedidos
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
